CSHS-CWRA/RavenPy

- ravenpy/tutorial.py
- requirements_dev.txt
- setup.py
- tests/common.py
- tests/test_base.py
- tests/test_tutorial.py
Fixes #16
- This ports the `raven` WPS project's `get_file` operations and implements them in the testing and file caching for the testing ensemble of RavenPy
- I've pinned Click below 8.0 as this is not yet compatible with `rasterio`, `xarray` and others.
> Add get_file operations for caching testdata files

- .cruft.json
- ravenpy/__version__.py
- requirements_dev.txt
- setup.cfg
- setup.py
`Bumpversion` is a tool we use to get around the problem of tracking/updating versions between releases.
https://github.com/c4urself/bump2version
The API is quite simple: `bumpversion major/minor/patch` will increment the semver part that you are interested in advancing. I have ported a piece of configuration that allows one to set a version as "release-ready" as well. Bumping major will set minor and patch both to `0`, minor will reset patch to `0`. It's pretty no-nonsense.
I have disabled tagging and committing by bumpversion since it doesn't play very well with `pre-commit` and `black` sometimes, but the process of releasing/tagging is not complicated is not complicated:
In other words, to create a new tagged release:
```
$ bumpversion minor
$ git commit -m "bumped version to …
```
> Use bumpversion

- HISTORY.rst
- ravenpy/utilities/regionalization.py
A better solution would be to run the different simulations in parallel, but let's open another issue for this.
> Fix caching bug in regionalization

- ravenpy/models/importers.py
- ravenpy/utilities/forecasting.py
- ravenpy/utilities/testdata.py
- tests/test_ECCC_forecast.py
- tests/test_NRCAN_daily.py
- tests/test_bias_correction.py
- tests/test_external_dataset_access.py
- tests/test_hindcasting.py
This PR : 
* Modifies a few tests so that they use `raven-testdata`
* Adds tests for the access of external datasets (ECCC, CASPAR)
* Makes `get_local_testdata` crash explicitly when it cannot find a file
* Fixes a typo
> Few fixes after 022

- setup.py
This should fix a pain point I had for a while: the inability to use `--install-option="--with-binaries"` in editable (aka. develop) mode. The overall solution is still not perfect of course, but at least this should make it easier for the most common scenario our users want: 
1. git clone
2. pip install in editable mode
3. getting the binaries.
> Allow installing binaries in develop/editable mode

- .cruft.json
- HISTORY.rst
- LICENSE
- docs/conf.py
- docs/installation.rst
- ravenpy/__version__.py
- ravenpy/utilities/__init__.py
- ravenpy/utilities/analysis.py
- ravenpy/utilities/checks.py
- ravenpy/utilities/forecasting.py
- ravenpy/utilities/geo.py
- ravenpy/utilities/geoserver.py
- ravenpy/utilities/io.py
- setup.cfg
- setup.py
- tests/test_geo_utilities.py
Are we ready for the minor increment?
> Release 0.3.0

- ravenpy/models/__init__.py
- ravenpy/models/base.py
- tests/test_base.py
- tests/test_emulators.py
This tries to make the RavenC error processing mechanism more explicit by doing two things:
1. Parse all the `Raven_errors.txt` messages
2. Coalesce the messages of type `ERROR` into a `RavenError` custom exception
The end goal of this is to catch this exception in RavenWPS and return it to the user as a `pywps.app.exceptions.ProcessError`, for friendlier debugging.
> Add RavenError and explicit Raven_errors.txt parsing

- .pre-commit-config.yaml
- ravenpy/models/commands.py
- ravenpy/models/emulators.py
- ravenpy/models/rv.py
- tests/test_emulators.py
This PR does two things:
- Updates the version of black in the pre-commit configuration. For information on the new features enabled by default, see: https://github.com/psf/black/releases/tag/21.4b0
- Updates the `isort` and `black` target python to the new lowest supported version (python3.7).
> update to newest black (v21.4b0) and use python3.7 import conventions

- HISTORY.rst
- ravenpy/config/commands.py
- ravenpy/config/rvs.py
- ravenpy/models/base.py
- ravenpy/models/emulators/blended.py
- ravenpy/models/emulators/gr4jcn.py
- ravenpy/models/emulators/hbvec.py
- ravenpy/models/emulators/hmets.py
- ravenpy/models/emulators/mohyse.py
- tests/test_emulators.py
- tests/test_geo_utilities.py
- tests/test_rv.py
Let's users compute diagnostics on user-defined periods. 
API change: model.diagnostics will return a dict of list instead of a dict of scalars. 
TODO: Tie into Ostrich.
> Added support for EvaluationPeriod

- HISTORY.rst
- ravenpy/utilities/geoserver.py
- tests/test_geoserver.py
This is a transitional set of fixes for backwards compatibility. Be aware that tests using `owslib<=0.24.1` and a newer version of GeoServer will fail.
> Owslib compatibility fixes

- environment.yml
- ravenpy/utilities/geoserver.py
- requirements_gis.txt
- setup.py
It seems that GeoPandas and ESMF/XESMF really do not like each other. I managed to get to the bottom of this using the GNU debugger. 
For reference, this is the stack trace when performing GeoPandas operating with ESMF installed: https://gist.github.com/Zeitsperre/d5d5f88be82835a47e48172f3bb7be16
And here's the working env without XESMF/ESMF: https://gist.github.com/Zeitsperre/e31c3f11b745856c655157d38ef4ec42
This is a sister PR to https://github.com/Ouranosinc/raven/pull/397
> Fix XESMF/ESMF and GeoPandas segfault

- .cruft.json
- environment.yml
- ravenpy/__version__.py
- ravenpy/utilities/forecasting.py
- requirements_gis.txt
- setup.cfg
- setup.py
We use CLISOPS for precisely one subsetting operation that can be replicated using xarray and rioxarray. CLISOPS is quite heavy on dependencies and has a few strange behaviours, like very aggressive logging (see: https://github.com/roocs/clisops/issues/144), that we don't need. Removing it means removing many libraries we don't already use.
> Remove clisops

- environment.yml
- ravenpy/utilities/regionalization.py
- setup.py
- tests/test_regionalisation.py
Replaced our in-house haversine calculation with something a bit more standard/precise. `Haversine` has no additional dependencies and is available on PyPI + conda-forge.
> Replace haversine function with Haversine library

- environment.yml
- setup.py
Opening this PR to give us some wiggle room in case #132 requires a fair amount of effort.
> Temporarily pin xclim below 0.29.0

- environment.yml
- setup.py
Pinning Climpred as it can accidentally pull in the newest xclim (v0.29) and we haven't adapted to the breaking changes yet. will need to addressed when tackling #132
> Pin climpred below v2.1.6

- ravenpy/utilities/data_assimilation.py
- tests/test_data_assimilation.py
The Data assimilation utilities were relatively simple and required users to setup long chains of processes to perform. The test case was particularly long, and had lots of direct modifications of the Raven model instance, in a complex loop.
I simplified this by adding functions in the data_assimilation utils that does this work for the user. The test-case has been simplified as well to make use of these tools. Now users can call the DA tools easily through Notebooks and ravenpy utils directly.
Next step will be to add a notebook to display the usage, which will come soon in the Raven-WPS repo.
> Add functionalities in Data Assimilation utils and simplify tests

- setup.py
The GDAL problems in RavenPy and on conda-forge have been an issue because of a handful of problems.
In a pure Python environment:
- The Python-GDAL and GDAL C-libraries need to match exactly in version number.
- The `pip` package resolver will always install the newest version of a dependency available on PyPI.
- The solution: pin the dependency of GDAL to the version of the C-library of GDAL at install time.
When a Python package is built on Anaconda:
- Different phases of the packaging process (`build`, `host`, `run`) can - and often do - have different versions, unless they are specifically pinned.
- The workaround: pin the package to specific versions and offer those as separate built binaries.
The issue here is that pinning packages to specific dependency versions will cause them to …
> Adjust handling of GDAL dependency when building RavenPy on conda-forge

- .pre-commit-config.yaml
- HISTORY.rst
- docs/ravenpy.cli.rst
- docs/scripts.rst
- ravenpy/__version__.py
- ravenpy/cli/__init__.py
- ravenpy/cli/generate_hrus_from_routing_product.py
- ravenpy/config/rvs.py
- ravenpy/models/base.py
- ravenpy/models/emulators/__init__.py
- ravenpy/utilities/coords.py
- ravenpy/utilities/data_assimilation.py
- ravenpy/utilities/forecasting.py
- ravenpy/utilities/geo.py
- ravenpy/utilities/graphs.py
- ravenpy/utilities/io.py
- ravenpy/utilities/mk_test.py
- ravenpy/utilities/nb_graphs.py
- ravenpy/utilities/regionalization.py
- ravenpy/utilities/testdata.py
- requirements_dev.txt
- tests/test_climatology_ESP_verfication.py
As discussed, here is the "magic" script for creating land/lake HRUs from a Routing Product V2.1 shapefile. I have cleaned it up a little, but haven't touched its core logic:
```
Usage: ravenpy generate-hrus-from-routing-product [OPTIONS] INPUT_FILE
Create a new HRU shapefile by splitting every subbasin row of a Routing
Product V2.1 shapefile into at least a land HRU and possibly an additional
lake HRU.
INPUT_FILE: Routing Product V2.1 shapefile (e.g.
"drainage_region_0003_v2-1/finalcat_info_v2-1.shp").
Options:
-o, --output PATH  Output shapefiles (will create a folder if no extension)
--help             Show this message and exit.
```
> Add generate-hrus-from-routing-product script

- HISTORY.rst
- README.rst
- environment.yml
- ravenpy/config/rvs.py
- ravenpy/models/base.py
- ravenpy/utilities/calibration.py
- setup.py
Spotpy calibration repeatedly calls model(), and each call, rv files are created and added to a zip file. As the zip file grows, adding new files slows down. In 0.8.0, I fixed this by skipping `merge_output` if `suppress_output` is True. This has the unintended side effect of breaking multiple tests in raven-wps and would be backward incompatible for raven-wps users, at least, without fixes to the wps handlers. 
The solution proposed here is to create another method `Raven._execute`, which runs the model but does not parse the outputs. The Spotpy calibration can use this method and avoid the slowdown problem. I've modified diagnostics so it parses output files on demand.
> undo suppress_output changes from 0.8.0, as it breaks raven-wps

- HISTORY.rst
- docs/usage.rst
- ravenpy/config/commands.py
- ravenpy/models/emulators/blended.py
- ravenpy/models/emulators/canadianshield.py
- ravenpy/models/emulators/gr4jcn.py
- ravenpy/models/emulators/hbvec.py
- ravenpy/models/emulators/hmets.py
- ravenpy/models/emulators/hypr.py
- ravenpy/models/emulators/sacsma.py
- ravenpy/utilities/data_assimilation.py
- tests/test_commands.py
- tests/test_data_assimilation.py
- tests/test_emulators.py
- tests/test_rv.py
**This is a breaking change.** 
Change the signature of HRUState. 
Instead of `HRUState(soil0=10)`, we now write `HRUState(data={"SOIL[0]": 10})`. 
Knowing which variables are specified, we're able to only put those in the rvc. This avoids warnings of `initial conditions for state variables not in model`. I think it's also a better design become the variable names are identical to those in the RavenC documentation.
> Refactor HRUState so that it prints only relevant state variables

- MANIFEST.in
- setup.cfg
- setup.py
This adds more clarity as to which files within RavenPy are listed as `data`. This should reduce build warnings on conda-forge when building packages, i.e. muting the following messages:
```
writing manifest file 'ravenpy.egg-info/SOURCES.txt'
/home/conda/feedstock_root/build_artifacts/ravenpy_1671727208024/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'ravenpy.data.hydrobasins_domains' as data is deprecated, please list it in `packages`.
!!
############################
############################
Python recognizes …
```
> Manifest updates

- docs/installation.rst
- environment.yml
@huard
I've released a new `RavenPy` conda package that lists `OSTRICH` as a `run_constrained` (optional) dependency, i.e. if the dependency is installed, ensure that a specific version of that dependency is installed alongside it. 
This means now that `ravenpy` installed via `$ conda install` must now explicitly install `ostrich` as well. This is now reflected in the docs via this PR.
I also removed the steps suggesting cloning the testing data. This has been obsolete for a few months, since #223.
> Update install and configuration instructions

- environment.yml
- setup.py
- tests/test_emulators.py
- tox.ini
* Use RavenC version 3.6
I needed to add some handling to patch the makefile to remove some compiler options. I would like us to remove this handling once we drop Ostrich and implement a Raven CLI command to perform the RavenC build step.
Changes in `setuptools` are gradually rendering all of our special handling obsolete. Ideally, we should consider dropping `setup.py` and `cmdclass` functionality altogether in a version not too far off.
> Use raven-hydro v3.6

- .github/workflows/main.yml
- ravenpy/config/commands.py
- ravenpy/extractors/forecasts.py
- ravenpy/utilities/forecasting.py
- requirements_dev.txt
- setup.cfg
- setup.py
- tox.ini
* Reinstates that Python3.8 is supported, adjust static types
* Re-adds Python3.8 to workflows
* Fixes a potential error that can happen with performing forecast analysis without `fiona` installed
* Pins `pip` below v23.1 as the newest changes deprecate `--install-options` 
https://github.com/pypa/pip/issues/11358
> Maintain Python3.8

- .github/workflows/publish-pypi.yml
- .github/workflows/tag-testpypi.yml
* Updates the publishing workflows to use `flit` and removes the need for installing GDAL to produce sdist/wheel packages
(Not a priority for the latest release, but will be good to have in time for the next one.)
> Update publishing workflows to reflect new structure

- .github/workflows/main.yml
- HISTORY.rst
- environment-rtd.yml
- environment.yml
- pyproject.toml
- ravenpy/utilities/testdata.py
- tests/conftest.py
* Integrate the `platformdirs` library for more intelligent/standardized testing data caching
Not really. Users can remove the `$HOME/.raven_testing_data` folder as the testing data is now saved in a much better spot, dependent on OS.
https://github.com/platformdirs/platformdirs
> Add platformdirs for consistent testing data caching

- .github/workflows/remove-obsolete-cache.yml
- .pre-commit-config.yaml
- HISTORY.rst
- environment.yml
* Adds a GitHub Workflow that removes caches from a branch when merged to the main branch
> Remove obsolete caches GitHub Workflow

- CONTRIBUTING.rst
- HISTORY.rst
- docs/installation.rst
- environment.yml
- pyproject.toml
- ravenpy/extractors/forecasts.py
- ravenpy/utilities/forecasting.py
- ravenpy/utilities/geoserver.py
- ravenpy/utilities/testdata.py
FYI @fmigneault
* The THREDDS and GeoServer instances can now be configured for staging/testing purposes. These new environment variables are documented within the installation docs:
* `RAVENPY_THREDDS_URL`: URL to the THREDDS-hosted climate data service. Defaults to `https://pavics.ouranos.ca/twitcher/ows/proxy/thredds`.
* `RAVENPY_GEOSERVER_URL`: URL to the GeoServer-hosted vector/raster data. Defaults to `https://pavics.ouranos.ca/geoserver`.
* This environment variable `GEO_URL` is still valid for legacy purposes.
* The `_determine_upstream_ids` function under `ravenpy.utilities.geoserver` was a direct copy of `determine_upstream_ids` found in `ravenpy.utilities.geo` and has been removed.
* The `get_CASPAR_dataset` and `get_ECCC_dataset` functions now accept a `thredds` and a …
> Configurable servers

- .cruft.json
- .github/workflows/main.yml
- .pre-commit-config.yaml
- HISTORY.rst
- ravenpy/__version__.py
- setup.cfg
- tests/test_calibration.py
> **Note**
> RavenPy v0.12.3 was never actually released!
> Prepare v0.12.3

- .coveralls.yml
- .github/workflows/main.yml
* Moves RavenPy Coveralls configuration entirely to env vars to evade a mysterious bug.
https://github.com/TheKevJames/coveralls-python/issues/252
> Fix Coveralls Workflows

- .readthedocs.yml
* Installs RavenPy using the ReadTheDocs `Python` block
Currently, the Jupyter (non-MyST) notebooks are not run (nbsphinx is not in the extensions. Is the plan to prgressively move these over to the MyST standard ?
> Fix notebook execution

- .github/workflows/main.yml
- .gitignore
- HISTORY.rst
- environment.yml
- pyproject.toml
- ravenpy/config/commands.py
- tests/conftest.py
- tests/emulators.py
- tests/test_commands.py
- tests/test_distributed_workflow.py
- tests/test_emulators.py
- tests/test_ensemble.py
- tests/test_forecasting.py
- tests/test_graphs.py
- tox.ini
- Added `h5netcdf` as a core dependency, acting as a backup engine for reading netcdf files.
- Made use of `model_copy(deep=True)` when dealing with Raven configs in the testing suite.
- Updated `autodoc-pydantic` for compatibility with `pydantic` v2.0+
- Modified some session-scoped `pytest` fixtures that were causing problems in other tests.
- Removed the redundant `emulators`-based `pytest` fixtures; These are now loaded from `emulators.py` in the `tests` folder.
> Refactor and simplify testing data fetching

- HISTORY.rst
- ravenpy/config/base.py
- ravenpy/config/commands.py
- ravenpy/config/emulators/hbvec.py
- ravenpy/config/utils.py
- tests/test_rvs.py
Should fix #340 
Adds a field validator on HRUs to ignore those with an hru_type that do not match expectations defined in the configuration. 
Emits a UserWarning if some HRUs are ignored.
> Filter HRUs with unrecognized hru_type attribute

- .github/workflows/main.yml
- HISTORY.rst
- environment-rtd.yml
- environment.yml
- pyproject.toml
- ravenpy/config/commands.py
- ravenpy/config/utils.py
- tests/test_commands.py
- tests/test_emulators.py
- tests/test_hindcasting.py
- tests/test_testdata.py
- tests/test_utils.py
- Added some development dependencies that were missing to the `environment.yml`
- Upgraded `owslib` to `>=0.29.1`
- All operations that open NetCDF files or DAP links accept an `engine` argument. The default for all of these is `h5netcdf`
- Added `pydap` as an alternate backend for opening DAP links
- `test_climpred_hindcast_verif` is now skipped for Python3.10 builds. It seems to only fail on the particular version of Python. When examining the dependencies, other than the Python version (and ABI version), there are no differences in the environments between Python3.10 and Python3.11. My gut feeling points to an issue with `climpred`.
- Temporarily disabled tests for macOS on GitHub due to architecture changes.
> Update dependencies, stabilize test

- HISTORY.rst
- docs/notebooks/time_series_analysis.ipynb
- ravenpy/config/commands.py
- ravenpy/config/utils.py
- ravenpy/ravenpy.py
- ravenpy/utilities/coords.py
- tests/test_commands.py
Fixed custom output command not rendering correctly
Convert config and output paths to absolute paths
> Bug fix for notebooks

- HISTORY.rst
- environment.yml
- pyproject.toml
See: https://github.com/Ouranosinc/xclim/issues/1771
> Pin pint below v0.24

- tests/test_emulators.py
Fixes #371 
TODO: review dependencies to make raven_hydro a "soft" dependency ?
> Fallback in test if raven_hydro is not installed

- CHANGELOG.rst
- environment-dev.yml
- pyproject.toml
- src/ravenpy/utilities/geoserver.py
- src/ravenpy/utilities/testdata.py
- tests/test_geo_utilities.py
- tests/test_geoserver.py
FYI @tlvu
- Removed the pin on `pyogrio` (set by `geopandas` now).
- Set base required `geopandas` to v1.0.
- Updated remote requests code to rely on `urllib{3}` instead of `requests`.
- Updated calls to remote GeoJSON file-like objects.
> Remove requests library, fix pyogrio calls, synchronize deps

- CHANGELOG.rst
- src/ravenpy/config/emulators/hbvec.py
Improved the HBV-EC emulator by adding parameter information (name, definition, and Raven default values) and fixed the variable name for the adiabatic temperature lapse rate.
This should not introduce breaking changes, and any errors would be captured by the tests already included in emulators.py.
> HBV-EC emulator improvements

- CHANGELOG.rst
- src/ravenpy/config/emulators/hbvec.py
Added an alias for rain snow fraction to match other emulators.
This minor change should not lead to any breaking changes and it should be covered by emulator tests already included in the repo.
> HBVEC emulator improvement

- .cruft.json
- CHANGELOG.rst
- pyproject.toml
- src/ravenpy/__init__.py
- tests/test_ravenpy.py
* Prepares the next minor release (v0.16.0)
No.
> Prepare v0.16.0

- CHANGELOG.rst
- src/ravenpy/config/emulators/hbvec.py
- src/ravenpy/config/rvs.py
* Reformatted the parameters class, hydro-meteorological processes, and soil parameters list. Slight adjustments were made to the parameter default, min and max values for indicative purposes, taking into account several sources of the Raven documentation.
* Added the spatial interpolation to the HBVEC emulator configuration explicitly, as well as the functionality necessary to the rvs.py configuration script. The default "INTERP_NEAREST_NEIGHBOR" interpolation was already executed implicitly by the model, but adding it in the model now gives users the flexibility to change the interpolation algorithm used if we wanted to.
* Reordered the soil classes to follow the progression of soil layers from shallow to deep (only cosmetic; no content change).
* Added the soil …
> Minor reformatting and changes to the HBVEC emulator

- .github/workflows/main.yml
- .pre-commit-config.yaml
- CHANGELOG.rst
- CONTRIBUTING.rst
- docs/configuration.md
- environment-dev.yml
- pyproject.toml
- src/ravenpy/config/base.py
- src/ravenpy/config/emulators/hbvec.py
- src/ravenpy/config/rvs.py
- src/ravenpy/config/utils.py
- tests/test_rvs.py
- tox.ini
- This PR fixes #418 
* Unpin pymbolic
* Resolve issue with `pymbolic > 2022.2`
* Tweaks to silence pydantic DeprecationWarning
Python3.9 support has been dropped.
> Fix issue #418. Unpin pymbolic. Resolve pydantic deprecation warnings

- CHANGELOG.rst
- environment-rtd.yml
- pyproject.toml
- src/ravenpy/utilities/graphs.py
- tests/test_graphs.py
* Fixes a `matplotlib` for v3.10+ compatibility.
* Pins `pygments` to avoid a breaking change affecting `sphinx-codeautolink`
No.
It's not entirely clear to me whether the dual histograms are being drawn properly to begin with. Alpha values from `ax` are the only ones that seem to matter when examining the graphic generated during tests.
> Fix matplotlib call

- src/ravenpy/config/emulators/__init__.py
* Removes the `pydantic`-defined models from the public API of `emulators`.
No. Usage still works, but documentation should be different.
The issue appears to be brought on because the `ListCommand` class can't serialize what `root` is when generating the documentation:
```python
lass ListCommand(RootModel, _Command):
"""Use so that commands with __root__: Sequence[Command] behave like a list."""
root: Sequence[Any]
def __iter__(self):
return iter(self.root)
def __getitem__(self, item):
return self.root[item]
def __len__(self):
return len(self.root)
model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)
```
This means that any emulated models built using it are raising errors when trying to parse the documentation. I'm not familiar enough with …
> Do not attempt to represent models due to non-serializable errors

- CHANGELOG.rst
- environment-dev.yml
- environment-docs.yml
- pyproject.toml
- This PR fixes https://github.com/Ouranosinc/pavics-jupyter-env-issues/issues/18
* Addresses an issue with some notebooks failing to build against the latest PAVICS alpha image
Not yet.
Private issue: https://github.com/Ouranosinc/pavics-jupyter-env-issues/issues/18
> Fix Jupyter Notebooks

- .readthedocs.yml
* Disable PDF generation
No.
The `latest` and `stable` builds of the documentation will try to build a PDF using LaTeX, and unfortunately it isn't clear why this is failing. There's likely a workaround that we can port from `xscen` or `xclim` to get it working again, but, in the meantime, we want the docs to be web-accessible at the very least.
> Disable PDF generation on ReadTheDocs

- .cruft.json
- .github/workflows/bump-version.yml
- .github/workflows/cache-cleaner.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/main.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/scorecard.yml
- .github/workflows/tag-testpypi.yml
- .pre-commit-config.yaml
- .zizmor.yml
- CHANGELOG.rst
- docs/conf.py
- pyproject.toml
- src/ravenpy/utilities/calibration.py
- src/ravenpy/utilities/coords.py
- src/ravenpy/utilities/geo.py
- src/ravenpy/utilities/geoserver.py
- src/ravenpy/utilities/regionalization.py
- tests/test_calibration.py
- tests/test_emulators.py
- tests/test_ravenpy.py
* Updates the cookiecutter template to the latest commit
* The CodeQL configuration has been replaced with a newer base template
* Adds two new hooks to pre-commit:
* `vulture`: for finding dead code blocks
* `zizmor`: for finding insecure workflow configurations
No. Function call signatures have not been changed.
Lots of a `FIXME` notices have been added for unused call signature variables. These should be addressed in the next major release.
`mypy` is staged, but the code base is far from being able to adopt it. We need to address a lot of typing issues.
I think we can safely tag a new version after this PR is merged.
> Update cookiecutter, mark dead code

- .github/workflows/publish-pypi.yml
- .github/workflows/tag-testpypi.yml
* Limits the Python version to 3.12 as not all CI dependencies are available for Python 3.13
No.
https://github.com/TheKevJames/coveralls-python/pull/542
> Limit python version for deployment

- docs/notebooks/00_Introduction_to_JupyterLab.ipynb
- docs/notebooks/02_Extract_geographical_watershed_properties.ipynb
- This PR fixes a portion of https://github.com/Ouranosinc/pavics-jupyter-env-issues/issues/23
* Slightly modified `00_Introduction_to_JupyterLab.ipynb` to not write to disk.
Not in my opinion. The example Markdown has been modified to suggest that users can write to their workspaces by modifying the example.
> Do not write to local disk in notebook 00

- .cruft.json
- CHANGELOG.rst
- pyproject.toml
- src/ravenpy/__init__.py
- tests/test_ravenpy.py
* Prepares the next patch release (v0.18.2)
No.
> Prepare v0.18.2

- CHANGELOG.rst
- src/ravenpy/config/commands.py
- tests/conftest.py
- tests/test_commands.py
- This PR fixes #500
* Bad default value for station_idx in the case of GriddedForcing.from_nc. 
Yes, this changes the default value for station_idx for ReadFromNetCDF. No test broke, so typical usage should not change.
> Set default station_idx to None for ReadFromNetCDF

- CHANGELOG.rst
- src/ravenpy/config/rvs.py
- This PR fixes #546 
* Adds a new command
No
> Gauged sub basin group
