CSHS-CWRA/RavenPy

environment.yml, setup.py
This addresses a desired library identified in https://github.com/Ouranosinc/raven/issues/336. I'm merging it based off of this branch, as the behaviour/enhancement (close-netcdf-files) is needed for it.
=> Add environment.yml and xskillscore and climpred to dependencies

.gitignore, ravenpy/cli.py, ravenpy/models/importers.py, tests/test_cli.py
This is a port of @julemai's latest grid weight generation script features into RavenPy. There are many things open to discussion!
=> Port of latest grid weight generation script features

ravenpy/models/base.py, ravenpy/models/emulators.py, ravenpy/models/multimodel.py, ravenpy/models/rv.py, ravenpy/utilities/forecasting.py, setup.py, tests/test_ECCC_forecast.py, tests/test_emulators.py, tests/test_hindcasting.py, tests/test_rv.py
See https://github.com/Ouranosinc/raven/pull/321
I'm including everyone involved for visibility. This is one of the last PRs before we remove what corresponds to this repo (i.e. RavenPy) from https://github.com/Ouranosinc/raven to make it depend on this one (sorry I'm sure there exists a better to say this).
=> Implement changes corresponding to Ouranosinc/raven PR #321

ravenpy/utilities/gis.py, ravenpy/utils.py
@huard @Zeitsperre Just for visibility.
=> RavenPy related parts of Fix 317

.readthedocs.yml, docs/installation.rst, environment-docs.yml, environment-rtd.yml, environment.yml, ravenpy/__init__.py, ravenpy/models/base.py, ravenpy/models/commands.py, ravenpy/utilities/regionalization.py, ravenpy/utilities/testdata.py, setup.py
After having had some trouble with the RTD build, I revisited the venv constraint for setup, and here's my proposition.
=> Remove the venv constraint for setup

.cruft.json, HISTORY.rst, ravenpy/__version__.py, ravenpy/models/base.py, setup.cfg, setup.py, tests/test_ECCC_forecast.py
Fix #46 
Related: https://github.com/Ouranosinc/raven/issues/197
=> Fix missing diagnostic file problem

tests/test_graphs.py
I think it makes more sense here.
Ref: https://github.com/Ouranosinc/raven/pull/351
=> Transfer test_graphs from RavenWPS here

ravenpy/utilities/data_assimilation.py
=> Reference -> References in docstring, to make Sphinx happy

ravenpy/models/base.py
=> fix _get_output bug

.github/workflows/main.yml, Makefile, ravenpy/utilities/__init__.py, ravenpy/utilities/nb_graphs.py, requirements_dev.txt, setup.py, tests/test_emulators.py, tests/test_geo_utilities.py, tests/test_nb_graphs.py, tox.ini
=> Enable GitHub CI

ravenpy/models/base.py
Simple fix to deal with {} found in comments inside non-templatable configuration files.
=> Fix base bugs

.cruft.json, .github/workflows/main.yml, HISTORY.rst, ravenpy/__version__.py, setup.cfg, setup.py
Please update the HISTORY file.
=> Release 0.4.0 (routing update)

ravenpy/utilities/geoserver.py
Just some call signature fixes for better IDE support when writing WPS processes in raven. Tied to changes in https://github.com/Ouranosinc/raven/pull/374.
=> Fix call signatures for hydrobasins

environment.yml, mypy.ini, ravenpy/cli/aggregate_forcings_to_hrus.py, ravenpy/config/commands.py, ravenpy/config/rvs.py, ravenpy/extractors/routing_product.py, ravenpy/models/base.py, ravenpy/models/emulators/blended.py, ravenpy/models/emulators/gr4jcn.py, ravenpy/models/emulators/hbvec.py, ravenpy/models/emulators/hmets.py, ravenpy/models/emulators/mohyse.py, ravenpy/models/multimodel.py, setup.py, tests/test_geoserver.py, tests/test_routing_lievre_tutorial.py
=> Changes to satisfy RavenWPS following 0.5.0 upgrade

ravenpy/models/emulators/gr4jcn.py, ravenpy/models/emulators/hbvec.py, ravenpy/models/emulators/hmets.py, ravenpy/models/emulators/mohyse.py
This just tries to remove some confusion.
=> Try to improve the RVC situation a little bit

setup.py
Addresses https://github.com/CSHS-CWRA/RavenPy/commit/027baf0a20fbb1e2a371ca35f275e9fd53a3bd43#r46530462
=> Use constant revision and version number at top of setup.py

ravenpy/cli/__init__.py, ravenpy/cli/collect_subbasins_upstream_of_gauge.py, ravenpy/cli/generate_grid_weights.py, ravenpy/config/commands.py, ravenpy/config/rvs.py, ravenpy/extractors/routing_product.py, ravenpy/models/base.py, ravenpy/models/emulators/blended.py, ravenpy/models/emulators/canadianshield.py, ravenpy/models/emulators/gr4jcn.py, ravenpy/models/emulators/hbvec.py, ravenpy/models/emulators/hmets.py, ravenpy/models/emulators/hypr.py, ravenpy/models/emulators/mohyse.py, ravenpy/models/emulators/sacsma.py, ravenpy/models/multimodel.py, ravenpy/utilities/regionalization.py, tests/test_base.py, tests/test_emulators.py, tests/test_routing_lievre_tutorial.py, tests/test_rv.py
@huard @julemai @dustming This is the beginning of the effort to support V2.1 of the Routing Product. Please help me to validate everything, and come up with a variation on the `test_routing_lievre_tutorial` with which to test it.
=> Support V2.1 of the Routing Product

environment.yml, ravenpy/utilities/geoserver.py, requirements_gis.txt
Some final cleanup of the dependencies before the next minor release. @cjauvin Feel free to push your final changes pre-0.7.0 here as well. I leave the merging to you.
=> Dependency cleanup

.cruft.json, .travis.yml, CONTRIBUTING.rst, README.rst, tox.ini
Just keeping the cruft recipe up-to-date
=> Cruft update

.cruft.json, .pre-commit-config.yaml, CONTRIBUTING.rst, tests/test_routing_lievre_tutorial.py
Some general updates. Closes #130
=> Update via cruft

.github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml
* Adds the VM fix workaround to the publishing workflows
=> add c-lib workaround to publishing workflows

ravenpy/models/emulators/blended.py, ravenpy/models/emulators/canadianshield.py, ravenpy/models/emulators/hbvec.py, ravenpy/models/emulators/hmets.py, ravenpy/models/emulators/mohyse.py, ravenpy/models/emulators/sacsma.py
Added references to the emulated hydrological models to complete this part of the docstrings, when possible.
Fixes #74 .
=> Added references to the emulated models

.editorconfig, docs/conf.py, environment.yml, ravenpy/models/base.py, ravenpy/utilities/forecasting.py, setup.cfg, setup.py, tests/test_emulators.py
Needed to update the location of the hindcast produced by GEPS. Causing failures in Raven: https://github.com/Ouranosinc/raven/runs/7509213903?check_suite_focus=true
=> Fix location of hindcast GEPS file

.github/workflows/main.yml, .pre-commit-config.yaml, MANIFEST.in, README.rst, benchmark/06_Raven_calibration.ipynb, docs/conf.py, docs/notebooks/Running_Raven_with_CANOPEX_data.ipynb, docs/notebooks/climatological_ESP_forecasting.ipynb, docs/notebooks/hydro_routing_product_example.ipynb, ravenpy/extractors/routing_product.py, ravenpy/utilities/geo.py, setup.cfg, setup.py
* Update to latest Ubuntu images
* Update cancel-workflow-action to 0.11.0
* Add NBQA and json-schema hooks to pre-commit
* Run hooks over code base
* fix some noqa warnings
=>  Update Actions and pre-commit hooks

ravenpy/models/base.py
=> Write docstring for `obj_func` Ostrich method

.github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml, environment.yml, setup.py, tests/test_config.py
=> Use xclim 0.39.0 and unpin pint

.github/workflows/main.yml, ravenpy/extractors/routing_product.py
Another step in bringing the master closer to the famine branch.
=> Import changes to routing product extractor from aida-famine branch

.github/workflows/main.yml, .pre-commit-config.yaml, setup.py, tox.ini
=> Pin setuptools in tox and in GitHub workflows

HISTORY.rst, ravenpy/utilities/graphs.py, ravenpy/utilities/nb_graphs.py, tests/test_graphs.py, tests/test_nb_graphs.py
=> Set check_missing to fit time series

HISTORY.rst, ravenpy/config/utils.py, tests/conftest.py, tests/test_utils.py
=> Handle scalar elevation values in nc_specs

.cruft.json, HISTORY.rst, ravenpy/__version__.py, setup.cfg
* Prepares the next patch release (v0.14.1)
FYI @tlvu
=> Prepare v0.14.1

.cruft.json, HISTORY.rst, ravenpy/__version__.py, setup.cfg
* Prepares the next minor version (v0.15.0)
=> Prepare v0.15.0

.github/workflows/scorecard.yml, CHANGELOG.rst, CODE_OF_CONDUCT.md, pyproject.toml, tox.ini
* Adds `setuptools` to the build recipe
* Fixes the trigger for the scorecard workflow
No.
Due to the fact that several different options exist for build backends, `setuptools` is no longer installed by default in newer versions of Python (3.12+).
=> Build fixes

.cruft.json, CHANGELOG.rst, pyproject.toml, src/ravenpy/__init__.py, tests/test_ravenpy.py
* Prepares the next patch version (v0.16.1)
* Corrects a misattributed change in the `CHANGELOG.rst`
No.
=> Prepare v0.16.1

.github/workflows/publish-pypi.yml, .github/workflows/tag-testpypi.yml
* Adds more connections to the allowlist when publishing versions
No.
=> Update allowed port connections

docs/notebooks/03_Extracting_forcing_data.ipynb
- This PR fixes https://github.com/Ouranosinc/pavics-jupyter-env-issues/issues/18
* Adds explicit chunking dictionary for cell in notebooks
No.
This change should be backwards-compatible.
=> Use explicit chunking configuration

.cruft.json, CHANGELOG.rst, pyproject.toml, src/ravenpy/__init__.py, tests/test_ravenpy.py
* Prepares the next minor version (for Monday, January 27th, 2025).
No.
=> Prepare v0.17.0

CHANGELOG.rst, docs/conf.py, environment-docs.yml, src/ravenpy/config/commands.py
=> Add parent Record class to _MonthlyRecord to fix autodoc error

.cruft.json, pyproject.toml, src/ravenpy/__init__.py, tests/test_ravenpy.py
* Prepares the next patch release v0.18.1
No.
=> Prepare v0.18.1

CHANGELOG.rst, src/ravenpy/config/rvs.py
- This PR fixes #489
* Added RelativeHumidityMethod to RVIs
No.
=> Added RelativeHumidityMethod to RVI config

CHANGELOG.rst, environment-dev.yml, pyproject.toml
* Pins `scipy` until `statsmodels` releases a fix.
No.
https://github.com/statsmodels/statsmodels/issues/9584
=> Pin scipy for statsmodels

.cruft.json, .github/workflows/cache-cleaner.yml, CHANGELOG.rst, pyproject.toml, src/ravenpy/__init__.py, tests/test_ravenpy.py
* Updates the version for release tomorrow (2025-07-16)
No.
A very small modification to a cache-cleaning workflow is also included. Has no impact on the library.
Coincidentally, both `raven` and `RavenPy` will share the same version and release date.
=> Prepare v0.19.0
